#!/bin/bash

set -e # If any command fails, stop execution of the hook with that error

db_user=`relation-get user`
db_db=`relation-get database`
db_pass=`relation-get password`
db_host=`relation-get private-address`

if [ -z "$db_db" ]; then
    juju-log "No database information sent yet. Silently exiting"
    exit 0
fi

if [[ -e "/home/diaspora/diaspora/.diaspora-db-setup-done" ]]; then
    juju-log "Database already setup, silently exiting"
fi

juju-log "Setting database credentials"
cd /home/diaspora/diaspora
sudo -u diaspora -H bash -c "cp config/database.yml.example config/database.yml"
# pgsql
sed --in-place "s/<<: \*mysql/#mysql/" /home/diaspora/diaspora/config/database.yml
sed --in-place "s/#<<: \*postgres/<<: \*postgres/" /home/diaspora/diaspora/config/database.yml
sed --in-place "0,/host: localhost/{s/host: localhost/host: \"$db_host\"/}" /home/diaspora/diaspora/config/database.yml 
sed --in-place "0,/username: postgres/{s/username: postgres/username: \"$db_user\"/}" /home/diaspora/diaspora/config/database.yml
sed --in-place "s/password: \"\"/password:/" /home/diaspora/diaspora/config/database.yml
sed --in-place "s/password:/password: \"$db_pass\"/" /home/diaspora/diaspora/config/database.yml
# TODO mysql
# sed --in-place "0,/host: \"localhost\"/{s/host: \"localhost\"/host: \"$db_host\"/}" /home/diaspora/diaspora/config/database.yml
# sed --in-place "0,/username: \"root\"/{s/username: \"root\"/username: \"$db_user\"/}" /home/diaspora/diaspora/config/database.yml
# sed --in-place "0,/password: \"\"/{s/password: \"\"/password: \"$db_pass\"/}" /home/diaspora/diaspora/config/database.yml

# sed --in-place "s/diaspora_production/$db_db/" /home/diaspora/diaspora/config/database.yml

# juju-log "DB name is $db_db"
touch /home/diaspora/diaspora/.db-available

juju-log "Launching diaspora upgrade"
$CHARM_DIR/hooks/upgrade-diaspora
