#!/bin/bash

set -e # If any command fails, stop execution of the hook with that error

# do some cleanup - we no longer have a db
cd /home/diaspora/diaspora
sudo -u diaspora -H bash -c "cp config/database.yml.example config/database.yml"

rm -f /home/diaspora/diaspora/.db-available
rm -f /home/diaspora/diaspora/.diaspora-db-setup-done

close-port 80
close-port 443
$CHARM_DIR/hooks/stop
