#!/bin/bash

set -e # If any command fails, stop execution of the hook with that error

db_user=`relation-get user`
db_db=`relation-get database`
db_pass=`relation-get password`
db_host=`relation-get private-address`

if [ -z "$db_db" ]; then
  juju-log "No database information sent yet. Silently exiting"
  exit 0
fi

juju-log "Setting database credentials"
sed --in-place "0,/host: \"localhost\"/{s/host: \"localhost\"/host: \"$db_host\"/}" /home/diaspora/diaspora/config/database.yml
sed --in-place "0,/username: \"root\"/{s/username: \"root\"/username: \"$db_user\"/}" /home/diaspora/diaspora/config/database.yml
sed --in-place "0,/password: \"\"/{s/password: \"\"/password: \"$db_pass\"/}" /home/diaspora/diaspora/config/database.yml
sed --in-place "s/diaspora_production/$db_db/" /home/diaspora/diaspora/config/database.yml

echo "DEBUG DB name is $db_db"

cd /home/diaspora/diaspora

if [[ ! -e ".diaspora-db-setup-done" ]]; then
    juju-log "Creating schema"
    sudo -u diaspora -H bash -c "source /home/diaspora/.bash_profile && rvm use ruby-1.9.3-p484 && RAILS_ENV=production  bundle exec rake db:schema:load"
    touch .diaspora-db-setup-done
fi

juju-log "Precompiling assets"
sudo -u diaspora -H bash -c "source /home/diaspora/.bash_profile && rvm use ruby-1.9.3-p484 && bundle exec rake assets:precompile"

juju-log "Make the application port available, now that we know we have a site to expose"

open-port 80
open-port 443