#!/bin/bash

set -e # If any command fails, stop execution of the hook with that error

db_user=`relation-get user`
db_db=`relation-get database`
db_pass=`relation-get password`
db_host=`relation-get private-address`

if [ -z "$db_db" ]; then
  juju-log "No database information sent yet. Silently exiting"
  exit 0
fi

juju-log "NOTE! DB cleanup not implemented yet - clean up old DB manually!"
#juju-log "Doing some database cleanup as relation is departing"
#cd /home/diaspora/diaspora
#DIASPORA_RUBY_VERSION=`cat .ruby-version`
#sudo -u diaspora -H bash -c "source /home/diaspora/.bash_profile && rvm use $DIASPORA_RUBY_VERSION && bundle exec rake db:drop"

#sudo -u diaspora -H bash -c "cp config/database.yml.example config/database.yml"
#rm -f /home/diaspora/.diaspora-db-setup-done
