#!/bin/bash

set -e

juju-log "Installing dependencies and upgrading system"
# TODO: make this optional for precise only
# apt-add-repository -y ppa:jaywink/curldebian
apt-get update && apt-get -y upgrade
# TODO: make libmysqlclient-dev / libpq-dev choice depending on db, now just pgsql
apt-get -y install build-essential git curl imagemagick libmagickwand-dev nodejs redis-server libcurl4-openssl-dev libxml2-dev libxslt-dev libpq-dev apache2 sendmail

if [[ ! -e /home/diaspora ]]; then
    juju-log "Adding diaspora user"
    useradd -m -s /bin/bash diaspora
fi

cd /home/diaspora/

if [[ ! -e /home/diaspora/.rvm ]]; then
    juju-log "Install RVM"
    sudo -u diaspora -H bash -c "gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3"
    sudo -u diaspora -H bash -c "curl -L https://get.rvm.io | bash -s stable"
    echo '[[ -s "~/.rvm/scripts/rvm" ]] && source "~/.rvm/scripts/rvm"' >> /home/diaspora/.bashrc
fi

$CHARM_DIR/hooks/upgrade-diaspora
