#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'

set -e

if [[ ! -e "/home/diaspora/.diaspora-db-setup-done" ]]; then
    juju-log "No database yet. Silently exiting"
    exit 0
fi

# Make sure we always use latest init
cp $CHARM_DIR/init/diaspora.conf /etc/init/diaspora.conf

# server needs to be restarted to make config relevant
juju-log "DEBUG: context id is $JUJU_CONTEXT_ID"
if [[ $JUJU_CONTEXT_ID != *"upgrade-charm"* ]]; then
    # we only want to restart if not upgrade-charm,
    # since otherwise it runs twice
    service apache2 restart
    service diaspora restart
    sleep 10
    juju-log "Diaspora server has been started"
else
    juju-log "DEBUG: skipping restart here since it will be done later"
fi

exit 0
