#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'

set -e

if [[ ! -e "/home/diaspora/.diaspora-db-setup-done" ]]; then
    juju-log "No database yet. Silently exiting"
    exit 0
fi

$CHARM_DIR/hooks/stop

service apache2 restart

cd /home/diaspora/diaspora
juju-log "Running script/server"
sudo -u diaspora -H bash -c "source /home/diaspora/.bash_profile && rvm use 2.0 && nohup DB=postgres ./script/server &"
sleep 10
juju-log "Diaspora server has been started"

exit 0