#!/bin/bash

set -e

# check some configs
if [[ -z `config-get hostname` ]]; then
    juju-log "Hostname needs to be specified in charm config. Silently exiting."
    exit 0
fi

juju-log "Making sure we've got latest rvm"
sudo -u diaspora -H bash -c "source /home/diaspora/.bash_profile && rvm get stable"

if [[ ! -e /home/diaspora/diaspora ]]; then
    juju-log "Check out diaspora source"
    cd /home/diaspora
    sudo -u diaspora -H bash -c "git clone -b `config-get branch` git://github.com/`config-get repository`.git diaspora"
    cd diaspora
    # set a git ident to make git happy in some situations when git pull force makes a merge
    sudo -u diaspora -H bash -c "git config user.email 'diaspora@jujucharm'"
    sudo -u diaspora -H bash -c "git config user.name 'Diaspora-Juju'"
fi

if [[ ! -e "/home/diaspora/diaspora/.db-available" ]]; then
    if [[ ! -e "/home/diaspora/diaspora/.diaspora-db-setup-done" ]]; then
        juju-log "No database yet. Silently exiting"
        exit 0
    fi
fi

cd /home/diaspora/diaspora

juju-log "Upgrading diaspora source"
if [[ -e ".diaspora-db-setup-done" ]]; then
    db_setup_done=yes
fi

# make sure we have the remote - in case config has a new repository
repository=`config-get repository`
if [[ `git remote -v | grep $repository | wc -l` -ne 2 ]]; then
    git remote set-url origin git://github.com/$repository.git
    git fetch origin
fi

# checkout correct branch
sudo -u diaspora -H bash -c "git reset && git checkout . && git clean -fd && git checkout `config-get branch` && git pull -f origin `config-get branch`"
if [[ ! -z $db_setup_done ]]; then
    touch .diaspora-db-setup-done
fi

$CHARM_DIR/hooks/diaspora-config

juju-log "Install or upgrade ruby gems"
sudo -u diaspora -H bash -c "source /home/diaspora/.bash_profile && rvm use 2.0 && bundle install --without heroku test development"

# make sure logrotate is enabled
if [[ ! -e "/etc/logrotate.d/diaspora" ]]; then
    juju-log "Configuring logrotate"
    sudo -u diaspora -H bash -c "source /home/diaspora/.bash_profile && rvm use 2.0 && bundle exec rake maintenance:install_logrotate_config"
fi

if [[ -z $db_setup_done ]]; then
    juju-log "Creating schema"
    sudo -u diaspora -H bash -c "source /home/diaspora/.bash_profile && rvm use 2.0 && bundle exec rake db:create db:schema:load"
    touch .diaspora-db-setup-done
else
    # we don't want to die if stopping fails
    set +e
    service diaspora stop
    set -e
    juju-log "Running database migrate"
    sudo -u diaspora -H bash -c "source /home/diaspora/.bash_profile && rvm use 2.0 && bundle exec rake db:migrate"
fi

juju-log "Precompiling assets"
sudo -u diaspora -H bash -c "source /home/diaspora/.bash_profile && rvm use 2.0 && bundle exec rake assets:precompile"

juju-log "Make the application ports available, now that we know we have a site to expose"
open-port 80
open-port 443

$CHARM_DIR/hooks/start
